### ISSUE TITLE
No matching version found for estraverse@5.0.0

### ISSUE THREAD

**Issue by ikomarov** [estools/estraverse#106]
No matching version found for estraverse@5.0.0 
 node -v
v12.5.0

**Comment by michaelficarra** [comment]
@ikomarov See https://github.com/estools/estraverse/commit/e3310506d0fd3502d6ed0e0f66cf492e57bb7302#commitcomment-37995495. How are you running into this?

**Comment by abhedsk** [comment]
No matching version found for estraverse@^5.0.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'esquery'

Got this error while getting latest eslint package installed.

**Comment by ikomarov** [comment]
Not relevant anymore
