### ISSUE TITLE
Why don't just fix the AST standard?

### ISSUE THREAD

**Issue by inf3rno** [estools/estraverse#25]
I don't understand the whole concept of estraverse. I mean it's like creating a SAX parser which iterates over the DOM. If I understand well, all of this is because the AST nodes do not have an uniform interface, like DOM nodes have e.g. childNodes, setAttribute, appendChild, etc.. Why don't you just fix the standard instead of creating such workarounds because of its errors?

**Comment by Announcement** [comment]
This is more of a complaint for [The ESTree Spec](https://github.com/estree/estree) @inf3rno
