### ISSUE TITLE
Add ExportNamedDeclaration

### ISSUE THREAD

**Issue by nzakas** [estools/estraverse#46]
This was just added to ESTree for module syntax.

```js
estraverse.Syntax.ExportNamedDeclaration = "ExportNamedDeclaration";
estraverse.VisitorKeys.ExportNamedDeclaration = ["declaration", "specifies", "source"];
```

https://github.com/estree/estree/blob/master/es6.md#exportnameddeclaration

estraverse fails with any AST that has this new structure at the moment.

**Comment by nzakas** [comment]
Also ExportDefaultDeclaration, maybe more.

**Comment by Constellation** [comment]
LGTM

**Comment by Constellation** [comment]
I'll add it :)

**Comment by ai** [comment]
Awesome! Release with this fix is soon?

**Comment by Constellation** [comment]
I'll publish it as `2.0.0` because it contains some breaking change.

**Comment by Constellation** [comment]
OK, I've submitted it as `2.0.0`.
