### ISSUE TITLE
Remove `require('./package.json')` from estraverse.js

### ISSUE THREAD

**Issue by natefaubion** [estools/estraverse#50]
When requiring estraverse for the browser via browserify/webpack, it includes the package.json in the build output. This can be fixed by a shim of some sort, but its mildly annoying.

**Comment by svenanders** [comment]
:+1: very annoying

**Comment by polkovnikov-ph** [comment]
:+1:

**Comment by hoschi** [comment]
@natefaubion which shim?

+1

**Comment by wilfrem** [comment]
:+1: 
webpack failed because of this issue.

**Comment by michaelficarra** [comment]
Closing, as this isn't an estraverse issue. A sufficiently advanced optimising compiler will load the JSON and strip any fields that are not accessed. If webpack is failing, open an issue on webpack.
