### ISSUE TITLE
Accessing parent of parent node, that's grand parent node

### ISSUE THREAD

**Issue by ncrichards** [estools/estraverse#55]
Thanks for the wonderful work.

Is it possible to access the parent of parent node?
### If the current node is 1 in the image below, is it possible to access node 5 ?

example: 

``` js
 ast = estraverse.replace(ast, {
            leave: function(node, parent, grand) {
                       console.log(grand);
              }
  }
```

Pls. can anyone help?
![tree](https://cloud.githubusercontent.com/assets/12530206/9155369/5c39909e-3ee8-11e5-931c-80b961a1304d.png)

**Comment by keyscores** [comment]
+1
@Constellation @RReverser  can we get some input if this is possible?

**Comment by RReverser** [comment]
You need to save it during `enter` phase yourself.
