### ISSUE TITLE
exports is undefined?

### ISSUE THREAD

**Issue by bluesheeva** [estools/estraverse#56]
Hi

I tried to use estraverse as external javascript library for a website that I develop. Whenever I call estraverse (estraverse.traverse), it gaves me an error: 'exports' is undefined. Can someone help with this? 

Here are my code:
<script type="text/javascript" src="plugins/esprima.js"></script>
<script type="text/javascript" src="plugins/estraverse.js"></script>
 var ast;
 ast = esprima.parse('var answer = 42;var answer2 = 45;function f(){var answer3;}');
 ast = JSON.stringify(ast);

var test;
        estraverse.traverse(ast, {
            enter: function (node, parent) {
                if (node.type == 'FunctionExpression' || node.type == 'FunctionDeclaration')
                    return estraverse.VisitorOption.Skip;
            },
            leave: function (node, parent) {
                if (node.type == 'VariableDeclarator')
                    test += node.id.name;
            }
        });

**Comment by twada** [comment]
I met the same problem yesterday and found that current estraverse codebase is not designed for web browsers. This is not a problem when we use browserify or webpack.

So I built estraverse by myself.

```sh
browserify --standalone estraverse node_modules/estraverse/estraverse.js > build/estraverse.browser.js
```

```html
<script type="text/javascript" src="../build/estraverse.js"></script>
```
works as expected.

**Comment by bluesheeva** [comment]
Hi twada. Thanks for your solution. It works!

I, however, found another error 'Unknown Node type null' whenever I try to traverse the AST generated by Esprima. I am not sure why the nodeType on line 510 in the estraverse source code always generates null value. My Esprima ast based on the code above is as follow:

{"type":"Program","body":[{"type":"VariableDeclaration","declarations":[{"type":"VariableDeclarator","id":{"type":"Identifier","name":"answer"},"init":{"type":"Literal","value":42,"raw":"42"}}],"kind":"var"}],"sourceType":"script"}

Any idea on this? Thanks

**Comment by bluesheeva** [comment]
Hi twada. It works!! thanks for the solution.
