### ISSUE TITLE
Release 4.1.1

### ISSUE THREAD

**Issue by silvenon** [estools/estraverse#59]
c074451e7ab80dcedac4115a10a2ea31138d515c fixes a very fatal bug in ESLint where parsing basic stuff like `export default` would crash. It would be so awesome is this change is released soon :+1:

**Comment by Constellation** [comment]
OK, lgtm.

**Comment by Constellation** [comment]
Released as `4.1.1`. Thanks for all!
@michaelficarra @dkoleary88 @mysticatea @pgilad

**Comment by silvenon** [comment]
Thanks!
