### ISSUE TITLE
Option to ignore properties in fallback="iteration" mode

### ISSUE THREAD

**Issue by nzakas** [estools/estraverse#67]
Right now, the option for `fallback: "iteration"` works great so long as all properties containing arrays/objects are intended to be traversed. However, there are some cases where extra information has been added into the AST (such as a `parent` property) where traversing according to regular rules isn't desirable.

I'd like to add an option that works only when `fallback: "iteration"` is set that allows us to ignore specific properties by name. So something like:

```js
controller.traverse(tree, {
    enter: function() {},
    exit: function() {},
    fallback: "iteration",
    ignoreKeys: [ "parent" ]
});
```

So `ignoreKeys` would be an array of keys that should never be traversed regardless of where they appear in the tree.

**Comment by michaelficarra** [comment]
I would much rather see `fallback` take a function from the object to the keys. We can continue to accept the string `"iteration"` for backwards compatibility, but in the future people should pass `Object.keys` in to get this behaviour.

**Comment by nzakas** [comment]
I'm not sure I understand what you're describing. Can you give an example?

**Comment by michaelficarra** [comment]
```js
controller.traverse(tree, {
  enter: function() {},
  exit: function() {},
  fallback: function(node) {
    return Object.keys(node).filter(x => x !== "parent");
  }
});
```

**Comment by nzakas** [comment]
Ah gotcha. Yeah, that's nicer.
