### ISSUE TITLE
4.2.0 breaking change

### ISSUE THREAD

**Issue by mathieudutour** [estools/estraverse#69]
Not sure what changed with the new minor version but it's breaking.

`Error: Unknown node type SpreadProperty.` 

eslint@2.3.0
estraverse@4.2.0
estraverse-fb@1.3.1
babel-eslint@4.1.8

Pinning to 4.1.1 fix it

**Comment by michaelficarra** [comment]
How are you calling estraverse? What are you calling it on?

**Comment by mathieudutour** [comment]
I am not calling it, I am calling eslint which is using estraverse

**Comment by michaelficarra** [comment]
Then you should open a bug with eslint. If they find a bug in estraverse, that is when a bug should be opened here.

**Comment by mathieudutour** [comment]
But nothing changed on eslint, I'm just saying that the new release of estraverse is breaking so it should be 5.0.0 instead of 4.2.0
