### ISSUE TITLE
estraverse ignores decorator in AST

### ISSUE THREAD

**Issue by otakustay** [estools/estraverse#70]
We have the below sample code:

```js
function dec() {
}

export default class Foo {
    @dec
    bar() {}
}
```

After parsed with `babel-eslint`, it contains a `MethodDefinition` node at `body[1].declaration.body.body[0]`, it has a `decorators` property, however `estraverse.traverse` just ignore this property

Is it possible that estraverse support the edge ECMAScript feature to visit `Decorator` node?

**Comment by twada** [comment]
[By passing `visitor.keys` mapping, we can extend estraverse traversing functionality](https://github.com/estools/estraverse#example-usage). In this case, you may use `require('babel-types').VISITOR_KEYS` as `keys`.

**Comment by otakustay** [comment]
Thanks, it seems this is an issue that `babel-types` does not include `decorators` field in `ClassMethod` type, I would create [an issue for that](https://phabricator.babeljs.io/T7281)
